# مرحلة بناء المشروع (إذا كان لديك أدوات بناء مثل Webpack أو Babel)
FROM node:18 AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .

RUN echo "Skipping build step, using plain HTML/CSS/JS"


FROM nginx:alpine

COPY ./src /usr/share/nginx/html


COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
